[package]
name = "hdp"
version = "2.4.0"
edition = "2021"

[dependencies]
socket2 = { version = "0.5.8", features = ["all"] }
atty = "0.2"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"
